@startuml

title Level start

start
:Level starts;
:NumberGenerator gets board
size (WxH);
:ValueGenerator generates WxH numbers,
based on a randomly chosen rule;
:ValueGenerator sends action, passing
the generated numbers;
:AppState gets a hold of numbers
and is updated;
:GameBoard gets notified of update and
places values in cells;
stop

@enduml
